name: Publish to PyPi

on:
  workflow_dispatch:
    inputs:
      active:
        description: 'Publish (tags only)'
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  test:
      name: Run all tests
      uses: ./.github/workflows/test.yml
  build-publish:
    name: Build and publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.head_ref || github.ref_name }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install build
      - name: Build sdist and wheel
        run: python -m build --sdist --wheel
      - name: Get artifact names
        run: |
          cd dist
          SDIST=$(python -c "import glob;print(glob.glob('*.tar.gz')[0])" 2>&1)
          WHEEL=$(python -c "import glob;print(glob.glob('*.whl')[0])" 2>&1)
          echo "SDIST=$SDIST" >> $GITHUB_ENV
          echo "WHEEL=$WHEEL" >> $GITHUB_ENV
          echo $SDIST
          echo $WHEEL
        shell: bash
      - name: Upload sdist artifact to GitHub
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.SDIST }}
          path: dist/${{ env.SDIST }}
      - name: Upload wheel artifact to GitHub
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.WHEEL }}
          path: dist/${{ env.WHEEL }}
      - name: Publish to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags') && github.event.inputs.active }}
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
