name: Publish to PyPi

on:
  workflow_dispatch:
    inputs:
      active:
        description: 'Publish (tags only)'
        type: boolean

jobs:
  test:
      name: Run all tests
      uses: ./.github/workflows/test.yml
  build-publish:
    name: Build and publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.head_ref || github.ref_name }}
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install build
      - name: Build sdist and wheel
        run: python -m build --sdist --wheel
      - name: Get artifact names
        run: |
          cd dist
          SDIST=$(python -c "import glob;print(glob.glob('*.tar.gz')[0])" 2>&1)
          WHEEL=$(python -c "import glob;print(glob.glob('*.whl')[0])" 2>&1)
          echo "SDIST=$SDIST" >> $GITHUB_ENV
          echo "WHEEL=$WHEEL" >> $GITHUB_ENV
          echo $SDIST
          echo $WHEEL
        shell: bash
      - name: Upload sdist artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SDIST }}
          path: dist/${{ env.SDIST }}
      - name: Upload wheel artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WHEEL }}
          path: dist/${{ env.WHEEL }}
      - name: Publish to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags') && github.event.inputs.active }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
