name: Publish to PyPi

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build (only uploads on tag)'
        type: string
        required: true

jobs:
  test:
      uses: ./.github/workflows/test.yml
  build-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install build
      - name: Build sdist and wheel
        run: python -m build --sdist --wheel
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
