name: Test

on: [push, pull_request, workflow_call]

permissions:
  contents: read

env:
  PACKAGE: radicli

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.13']
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
        with:
          submodules: true
      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install build
      - name: Run pyright
        run: python -m pyright ${{ env.PACKAGE }}
      - name: Build sdist
        run: python -m build --sdist
      - name: Remove package directory
        run: rm -rf ${{ env.PACKAGE }}
        shell: bash
      - name: Install from sdist
        run: pip install dist/*.tar.gz
        shell: bash
      - name: Run pytest
        run: python -m pytest --pyargs ${{ env.PACKAGE }}
