name: Test

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: pip install -r requirements.txt
      - name: Run pyright
        run: python -m pyright radicli
      - name: Build sdist
        run: python setup.py sdist
      - name: Remove package directory
        uses: JesseTG/rm@v1.0.3
        with:
          path: radicli
      - name: Install from sdist
        run: pip install dist/*.tar.gz
      - name: Run pytest
        run: python -m pytest --pyargs radicli
